### ISSUE TITLE
怎么关闭某个容器呢

### ISSUE THREAD

**Issue by atmoxao** [wenshunbiao/docker#1]
# 如题

我关闭了某个docker容器又会自动重新重启，杀不掉？

**Comment by wenshunbiao** [comment]
@Paccco 该项目使用 `system` 来守护进程，您可以使用 `p` 快捷命令来结束服务，以结束 `redis` 服务为例：执行 `p redis` ，它等同于 `systemctl stop redis && systemctl disable redis`，详细shell内容可查看 `/home/core/docker/shell/p`

**Comment by atmoxao** [comment]
谢了朋友，有没有内置一键卸载，还原安装时候备份的文件的脚本呀 太多了 根本用不上

**Comment by wenshunbiao** [comment]
@Paccco 需要卸载本项目，先使用`p`停止所有服务，然后直接删除目录即可，注意检查文件夹内是否有需要备份的数据：
```
rm -rf /home/core && mv -f /root/.bashrc.bak /root/.bashrc && source /root/.bashrc
```
